### ISSUE TITLE
GitHub Project and Kanban Setup

### ISSUE THREAD

**Issue by julie-ify** [julie-ify/JavaScript-Capstone-project#21]
Here is the link to our [project](https://github.com/julie-ify/JavaScript-Capstone-project/projects/1)

I have only one team member, that is to say, that we are only two members in my team. Thank you.

**Comment by Davidosky007** [comment]
## Hi @julie-ify 👋, 


Good job so far! 💪 
* Nice job with the project descriptoion ✔️ 
* professional-looking repository ✔️ 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
* Kindly make the number of cards 17 for two members as it is required to properly distribute tasks 
* Each of the team members should assign themselves to the cards from all categories: (ie Setup, Fetch data, Lists render, Actions, Conditional components, Filters).
* i suggest you add an assignee with an  avatar with the assignee's image like this 
![image](https://user-images.githubusercontent.com/52497246/132224867-04a1f648-2be1-41a7-ab49-98e7d4269d1d.png)

![image](https://user-images.githubusercontent.com/52497246/132224074-0d74e9da-34c2-442a-ba64-f28d76e65147.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by julie-ify** [comment]
Hi @Davidosky007 
Thanks for reviewing our setup. But the tasks for two team members after removing all the tasks with student c is 15 tasks. We have 15 tasks for only two team members. Please check again and give us feedback. Thanks

**Comment by Davidosky007** [comment]
> Hi @Davidosky007
> Thanks for reviewing our setup. But the tasks for two team members after removing all the tasks with student c is 15 tasks. We have 15 tasks for only two team members. Please check again and give us feedback. Thanks

so sorry for the mistake it should be 15 cards for two members kindly make the other changes and submit for a review 🙏

**Comment by julie-ify** [comment]
Ok, Thanks.

**Comment by henatan99** [comment]
Hi @julie-ify && @TedLivist , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

- [ ] OPTIONAL: The link you have provided in the issue comment field is wrong. Kindly make changes even though your project is approved. I think the correct project link is [here](https://github.com/julie-ify/JavaScript-Capstone-project/projects/1). :pray: 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by julie-ify** [comment]
Ok, thanks.
